feat: add final ci job that depends on everything for github to use to enforce CI passes on PR

diff --git a/.github/workflows/node-ci.yml b/.github/workflows/node-ci.yml
--- a/.github/workflows/node-ci.yml
+++ b/.github/workflows/node-ci.yml
@@ -298,3 +298,18 @@ jobs:
         run: |
           git diff --exit-code infra/scribear-db/src/database.types.ts || \
           (echo "Error: Generated database types are out of date. Run 'npm run generate:types' in infra/scribear-db and commit the changes." && exit 1)
+
+  ci:
+    needs: [format, lint, build, test, docker-build, integration-test, check-database-types]
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check All Jobs Pass
+        run: |
+          results="${{ join(needs.*.result, ' ') }}"
+          for result in $results; do
+            if [ "$result" != "success" ] && [ "$result" != "skipped" ]; then
+              echo "Job failed with result: $result"
+              exit 1
+            fi
+          done
diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -115,3 +115,18 @@ jobs:
         with:
           package_name: "Transcription Service - Integration Tests"
           filename: "./transcription_service/coverage.xml"
+
+  ci:
+    needs: [format, lint, test, docker-build, integration-test]
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check All Jobs Pass
+        run: |
+          results="${{ join(needs.*.result, ' ') }}"
+          for result in $results; do
+            if [ "$result" != "success" ] && [ "$result" != "skipped" ]; then
+              echo "Job failed with result: $result"
+              exit 1
+            fi
+          done
